import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { AppProvider } from "@/components/providers";
import { AppHeader } from "@/components/headers/app-header";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create-next-app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased">
        <AppProvider>
          <AppHeader />
          <NuqsAdapter>{children}</NuqsAdapter>
        </AppProvider>
      </body>
    </html>
  );
}